name: Continuous Integration (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML structure
        run: |
          echo "Verificando se o arquivo index.html existe..."
          if [ -f site/index.html ]; then
            echo "Arquivo index.html encontrado com sucesso!"
          else
            echo "Erro: index.html não encontrado na pasta site/."
            exit 1
          fi

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: site/
          
